### ISSUE TITLE
compile error(but complile arkcore is ok)

### ISSUE THREAD

**Issue by mygithome002** [jubel02/NomadicWow#1]
**Description**:player.cpp compile error:illegal case ...;
**Current behaviour**: win8.1;VS2013 community;mysql 5.6.27;cmake 3.6.3
**Expected behaviour**: 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**ArkCore commit / Repack core & DB version**:  jubel02/NomadicWow

**Comment by jubel02** [comment]
Oh ok let me check!

**Comment by jubel02** [comment]
Fixed in 90f73ea684aa2c506f43292ea9b60f83d13ada5a
